sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
install:
  - bundle install --retry=3
  - rake db:create
  - rake db:migrate
  - rake db:seed
script:
  - bundle exec rspec
  - bundle exec rubocop
