default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cyberbrain_development

test:
  <<: *default
  database: cyberbrain_test

production:
  <<: *default
  database: gis_cyberbrain
